language: python
python:
    - '3.7'
dist: bionic

before_install:
    # steps taken from https://docs.mopidy.com/en/latest/installation/pypi/
    - sudo apt install -y python3.7
    - sudo add-apt-repository universe
    - sudo apt install -y build-essential python3-dev python3-pip
    - sudo apt install \
        python3-gst-1.0 \
        gir1.2-gstreamer-1.0 \
        gir1.2-gst-plugins-base-1.0 \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-tools
    - sudo python3.7 -m pip install --ignore-installed mopidy
    - sudo apt install -y \
        libcairo2-dev \
        libffi-dev \
        libgirepository1.0-dev \
        libglib2.0-dev \
        python3.7-dev
    - sudo python3.7 -m pip install --ignore-installed --no-cache pygobject
    - wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gst-python1.0/python3-gst-1.0_1.14.4-1_amd64.deb
    - ar x python3-gst-1.0_1.14.4-1_amd64.deb
    - tar -pxvf data.tar.xz
    - sudo mv usr/lib/python3/dist-packages/gi/overrides/* /usr/local/lib/python3.7/dist-packages/gi/overrides/
    - wget https://apt.mopidy.com/dists/buster/main/binary-amd64/mopidy_3.0.1-2_all.deb
    - sudo dpkg -i mopidy_3.0.1-2_all.deb
    - sudo apt install --fix-broken
    - sudo dpkg -i mopidy_3.0.1-2_all.deb
    - sudo sed -i 's/python3/python3.7/' /usr/bin/mopidy
    - sudo apt autoremove \
        libcairo2-dev \
        libffi-dev \
        libgirepository1.0-dev \
        libglib2.0-dev

install:
    - bin/raveberry system-install-default
script: ":"

#before_deploy:
#    - yarn install
#    - mkdir raveberry
#    # move all files except the setup.py and the newly created folder
#    - mv `\ls -A1 | grep -v -E '(setup.py|raveberry)'` raveberry
#deploy:
#    provider: pypi
#    user: __token__
#    password:
#        secure: mL1pNF6otGu3RFwJmVOY1OjwUq92Iy8F/XksSLBeAcChMXRQElcArXywwdSkwRxrw87fIN8MW5BnFiKkqw6kRcUciwPJDBlr6o2E1pVJqnpzhHfAPZQan/KQmDLNl1RRRhdjdUkFXn/fCVAo2WoGhcFyreJ1+vfZwlqwzTScw5alZB2bFSL2YS+cO4PEXa86C4W5NSF3kN6tqUK0SR3Q2bc/RLdenMPkaRfD2IhDYdMcmhhbRv/oXyTJrJxHx0fwTAvqWW+gahsbYSAXsfrRubFtEGWYVrQZARwOdgMoVtTK6GxU6VbdG8gkyLy7yJ9U+VMv8sjopzK5fLVl1wPp7Igq6YoDgRt5T832OPIiyhszwT8GziSJ8FLtr9gf3gZcBvt1Fpj/TcgewmvTrQn0KPzSIzq0qXufaDESB3KwqdUrevWNldvAzLBrX9R0JYEyCy1n5Q8bY7b/GVuhMVRa1Uzk9tS8teXmD9uRHMr4FyYbKiT9S0MEE/YTDNn8ggbOSL0POdytVh6moWFvECC+9+wh4+E4K4ywI6/P9uWhw3RwVVXJhsyo7UZRDDDMs/KiH+r56uVp7MOpsud8i9hpivZE+iF1zeZ8UsRyhy68gp9MQ/1zm5ltP+173Sce2r1cBOKHITF15AqUaMLCq5eosZ/nm7uzzwJs9DLQxmcBW58=
#    server: https://test.pypi.org/legacy/
#    skip_cleanup: true
#    distributions: "sdist bdist_wheel"
#    skip_existing: true
