language: python
python: "3.7"

install: ":"
script: ":"

deploy:
  provider: pypi
  user: __token__
  password:
    secure: "invalid"
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  server: https://test.pypi.org/legacy/
