language: python
python: "3.7"

install:
    - yarn install
script: ":"

before_deploy:
    - mkdir raveberry
    # move all files except the setup.py and the newly created folder
    - mv `\ls -A1 | grep -v -E '(setup.py|MANIFEST.in|raveberry)'` raveberry
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "H6C72f3wlMK4VqQey+AHoQUplDXaz//1ig43Y6Oc2pMwEv2wry7pmVc1RN/PpPaROc4H6fZDc+cOGy+TqKfQ9NTk0k2MVlCgjAVkGHulX4CIW7Z/mOI+5ODgDGOGtkwZA6WjPptXD42gq1Iv5sU/aP7839xNY3rvQEjo1mma2c9wNGwM9LnlmPP69JhWBQjxoHG17KOJQA1QfWeVQYWUwOoXSmh0BePCqA3RMJm59yvPsRWtWmcMVPmxPL/L2iN6rCyRRQiDZgA3uPfmHVLUesHqQ4QtYury24Prr1v3dXoDz8pkdmpCga/ewaQ6Bit8+q3PSQGcTahwV9uvRovdN28hb0ZTsZ7Ee78czm9Lt3iBcSyilyQ3eIP+v7gpPWAK7VGGGox1qb4njGRhHyz4x4nM6+IrfpIk2ZBJfp0lN9zDCBQHdgh/d7ZL5hprJjJdFIDKC66Mu0vwp8jEVHLhqUrw7B/jmQuXtSS7dyZRI40l0Plwmsa1/zIFeBZDi5bXSyRf04vE7iW7pO5fKeKgT71KtWlpZKo1fqUibrmoe2QO79C7vS/XKVM4zR4ZBVix212IPM73raL0i2146c0h5mwkkwkEpPNsWos486UvUl97MgELxWqH7OD0voOxyRzQUpR+yRS8+Azrc+SS4BECXPvZlCRu4n/HpUH7a7IXep0="
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
