language: python
python: "3.7"

install: ":"
script: ":"

deploy:
  provider: pypi
  user: __token__
  password:
    secure: "bEE8Mz4vBonYb18Zzntmys6zpVd5z7sRUYf9dAP+vwwXO92GhLdsI8JIVtgdxPynBLTf3N9NtGkOodYaMixLzNZRRbKTsROosXI55zWUBHl8hSBWnPzoRQGO7xg/HgW9fh0mNPmLGLUAbKieRpsO1Ala6E9LC8yQ/Ax+nNajddPjQE1omEe3qNXjHdsykviBKLisHuWnIJpgpdVf1g60u4U24JGfYtu25t6SBBIxAWZWkKFNw7Gya3pu9ttrdiAtU0+SsMOGmde7wVO1ff6+NyhlJVb3fWhYdzl7CzY5IgE+s9DQL3mV+NSmaqcTtAqmBjf7RyQoF34mteTnvpp9qZEncqdjhovcDfqEJ2KFNQ5M3lQhcrIA57t4XifuuxVxvI+nZpTBwVRaUjZzBtF0VI7j6YxK4AOS8OlXG4enoPT0TXJGqCCiu6INiCG3cFrRGUH4i6mfjcDe36hU1K5/OWL2MzXhbqf84hzFzh2XZC8m9/DWxrI73z2Tzb7el+tTSDlma5uZUD25QvtzZIylIcB8frNHbveeHtqItQerintZyPDnNaP5WAk0V4ximE2Mfwf6yR31/SJBKmEV067rByuDqLf0DdrxV1M3VqoLLoCHT3Nh07bhqUZXrfPdC77pAP5yEjeJRjFgdhCHKute2NT48+kPDwwzTNAJ8c2xF9g="
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  server: https://test.pypi.org/legacy/
