name: Raveberry Deploy
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
jobs:
  #test-frontend:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-python@v2
  #      with:
  #        python-version: '3.7'
  #        architecture: 'x64'
  #    - uses: actions/setup-node@v2
  #      with:
  #        node-version: 'lts/*'
  #    - name: Install pip dependencies
  #      run: |
  #        pip install -U pip
  #        pip install -r requirements/ci.txt
  #    - run: yarn --cwd frontend install
  #    - run: yarn --cwd frontend build
  #    - run: yarn --cwd frontend test
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
      redis:
        image: redis
      mopidy:
        image: raveberry/raveberry-mopidy
        env:
          MOPIDY_OUTPUT: fakesink sync=true
    env:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install pip dependencies
        run: |
          pip install -U pip
          pip install -r requirements/ci.txt
      - run: >
          sudo apt-get -y install
          ffmpeg
          gstreamer1.0-plugins-bad
          libpq-dev
      - name: Prepare database
        run: |
          psql -h postgres -c "CREATE USER raveberry WITH PASSWORD 'raveberry';"
          psql -h postgres -c "CREATE DATABASE raveberry;"
          psql -h postgres -c "ALTER USER raveberry CREATEDB;"
          python manage.py migrate
          python manage.py installwatson
          python manage.py buildwatson
      - run: python manage.py test

