name: Publish Raveberry
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: pip install -r backend/requirements/frontend_build.txt
      - run: yarn --cwd frontend install
      - run: yarn --cwd frontend build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-files
          path: |
            backend/static/bundle.js
            backend/static/style.css
            backend/static/*.woff2
  test-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/download-artifact@v4
        with:
          name: frontend-files
          path: backend/static/
      - run: pip install -r backend/requirements/frontend_test.txt
      - run: yarn --cwd frontend install
      - run: yarn --cwd frontend test
