name: Publish Raveberry
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install pip dependencies
        run: pip install -r backend/requirements/install.txt
      - run: sudo apt-get update
      - run: sudo systemctl start postgresql
      - run: |
          (while true; do df -h; sleep 5; done) &
          bin/raveberry --confirm-config --use-default-password-i-promise-ill-change-it install
      - name: Check if server is up
        run: |
          counter=0
          until [[ $(curl -sS http://localhost/api/version/) == "Raveberry version"* ]] || [ $counter -gt 30 ]
          do
            counter=$((counter + 1))
            sleep 1
          done
          # exit with failure if curl did not succeed in any iteration
          [ $counter != 31 ]
