name: Publish Raveberry visualization
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      # TODO
      #build:
      #  runs-on: ubuntu-latest
      #  strategy:
      #    matrix:
      #      python: ["3.8", "3.9", "3.10"]
      #  steps:
      #    - uses: actions/checkout@v2
      #    - uses: actions/setup-python@v2
      #      with:
      #        python-version: ${{ matrix.python }}
      #    - uses: actions-rs/toolchain@v1
      #      with:
      #        toolchain: stable
      #        profile: minimal
      #        override: true
      #    - run: pip install wheel setuptools_rust
      #    - run: python setup.py sdist bdist_wheel
      #    - run: ls -la dist/
      #    - uses: actions/upload-artifact@v2
      #      with:
      #        name: dist
      #        path: |
      #          dist/static/*
  crosscompile:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cross
        run: cargo install cross
      - run: pip install setuptools-rust
      - name: Build wheel using cross
        shell: bash
        env:
          CARGO: cross
          CARGO_BUILD_TARGET: aarch64-unknown-linux-gnu
          PYO3_CROSS_LIB_DIR: /opt/python/cp38-cp38/lib
        run: |
          docker build -t cross-pyo3:aarch64-unknown-linux-gnu .
          python -m pip install wheel
          python setup.py bdist_wheel --plat-name manylinux2014_aarch64
          ls -la dist/
