name: Publish Raveberry
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install pip dependencies
        run: pip install -r backend/requirements/install.txt
      - run: sudo apt-get update
      - name: remove pyyaml
        run: |
          sudo rm -rf /usr/lib/python3/dist-packages/yaml
          sudo rm -rf /usr/lib/python3/dist-packages/PyYAML-*
      # https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check
      - name: Fix preinstalled apt dependencies
        run: |
          sudo apt-get --reinstall install python3-apt
          sudo apt-get --reinstall install python3-pip
          sudo apt-get --reinstall install apt-transport-https
          sudo apt-get install build-essential libssl-dev libffi-dev
      - name: Self update pip
        run: sudo pip install -U pip
      - name: Fix preinstalled pip dependencies
        run: sudo pip install pyopenssl --upgrade
      - run: sudo systemctl start postgresql
      - run: bin/raveberry --confirm-config --use-default-password-i-promise-ill-change-it install
      - name: Check if server is up
        run: |
          counter=0
          until [[ $(curl -sS http://localhost/api/version/) == "Raveberry version"* ]] || [ $counter -gt 30 ]
          do
            counter=$((counter + 1))
            sleep 1
          done
          # exit with failure if curl did not succeed in any iteration
          [ $counter != 31 ]
